### ISSUE TITLE
[BUG]: 如果没pull就push就会炸掉

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/Fufu_Dev_Tools#21]
### 在继续之前，请确认以下内容

- [X] 我已经搜索过已存在的问题，并没有存在相同的正在进行中/重复/已解决的问题
- [X] 如果该问题在预览版中被解决，我没有被告知

### 选择一个问题类别

使用问题

### 描述你遇到的问题

```
重试中........
✕ 第 4 次推送尝试失败，出现了非已知网路问题
[提示] 如果你确定这是网络问题，请提交issue或者PR，感谢！
原因:
To https://github.com/.../...
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/.../...'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Traceback (most recent call last):
  File "plyer\utils.py", line 96, in _ensure_obj
ModuleNotFoundError: No module named 'plyer.platforms'
Traceback (most recent call last):
  File "连续push尝试.py", line 101, in <module>
  File "连续push尝试.py", line 87, in main
  File "plyer\facades\notification.py", line 84, in notify
  File "plyer\facades\notification.py", line 93, in _notify
NotImplementedError: No usable implementation found!
[PYI-9220:ERROR] Failed to execute script '??push??' due to unhandled exception!
```

### 描述如何重现你遇到的问题

在远端有新修改时，不pull，直接使用`ffdev 连续push`来push

### 实际行为

/

### 预期行为

弹出消息提醒

### 确认相关信息

```raw
> ffdev --version
✓ 版本: 2024.09.26.2000
✓ 安装在: ...
```

**Comment by DuckDuckStudio** [comment]
## 详细排查

- 错误原因：
未处理的异常导致无法发出提醒...?

- 初步检查代码:
未找到问题

**Comment by DuckDuckStudio** [comment]
@fjwxzde run test --file "开发工具-源码\git\连续push尝试.py"

**Comment by DuckDuckStudio** [comment]
正常推送都会...?!
![image](https://github.com/user-attachments/assets/414519cc-ad65-40c8-ac8f-dc6fc6c96643)

**Comment by DuckDuckStudio** [comment]
++，竟然是打包脚本的问题...
